export const approvalToolPhrases: Record<string, string> = {
  audio_read: 'Read audio',
  browser_action: 'Use the browser',
  coding_agent: 'Start a coding tool',
  code_diagnostics: 'Run code analysis',
  connector_action: 'Use a connected service',
  desktop_action: 'Use the desktop',
  desktop_launch: 'Open an application',
  file_patch: 'Apply a file change',
  file_write: 'Write a file',
  generate_media: 'Generate media',
  memory: 'Update memory',
  parallel_web_read: 'Read web sources',
  print_pdf: 'Print a PDF',
  process: 'Resume a checkpoint command',
  publish_artifact: 'Publish a file',
  publish_preview: 'Publish a preview',
  schedule: 'Schedule work',
  shell: 'Run a command',
  skill: 'Update a skill'
};
